[package]
name = "ch03e-efficient-broadcast-part-two"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.28.1", features = ["full"] }
